language: rust
matrix:
  include:
    - rust: "nightly"
      env: TEST_SUITE=suite_nightly
    - rust: "beta"
      env: TEST_SUITE=suite_beta
    - rust: "stable"
      env: TEST_SUITE=suite_stable
